export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REGISTER_REQUEST = "REGISTER_REQUEST";

//ADMIN
export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";
export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST";
export const ADMIN_ENABLE_USER_REQUEST = "ADMIN_ENABLE_USER_REQUEST";