export const SET_REQUEST = "SET_REQUEST";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_FAILED = "SET_FAILED";

export const SET_LOGOUT = "SET_LOGOUT";

//ADMIN
export const SET_USERS_SUCCESS = "SET_USERS_SUCCESS";
export const SET_STATE_USER = "SET_STATE_USER";